import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    'nav.services': 'Serviços',
    'nav.differentials': 'Diferenciais',
    'nav.pricing': 'Planos',
    'nav.about': 'Sobre nós',
    'nav.contact': 'Fale conosco',
    'hero.title': 'os talentos certos para',
    'hero.title.highlight1': 'Contrate',
    'hero.title.highlight2': 'acelerar',
    'hero.title.end': 'o crescimento da sua empresa',
    'hero.subtitle': 'Conectamos empresas e startups em fase de tração ou scale-up a profissionais altamente qualificados, com foco em agilidade e assertividade no processo de contratação.',
    'hero.cta1': 'Agende uma reunião',
    'hero.cta2': 'Conheça nossos serviços',
    'services.title': 'Headhunting Especializado',
    'services.subtitle': 'Busca ativa de talentos alinhados ao perfil comportamental e técnico da sua empresa, com match perfeito para crescimento acelerado.',
    'services.process.title': 'COMO FUNCIONA NOSSO PROCESSO:',
    'services.process.step1.title': 'Entendimento do perfil',
    'services.process.step1.description': 'Compreendemos profundamente as necessidades técnicas e comportamentais da sua empresa, cultura organizacional e objetivos de negócio.',
    'services.process.step2.title': 'Busca qualificada',
    'services.process.step2.description': 'Utilizamos nosso banco de talentos e metodologias avançadas para encontrar profissionais que se encaixam perfeitamente nos requisitos definidos.',
    'services.process.step3.title': 'Entrevistas e seleção',
    'services.process.step3.description': 'Realizamos triagens técnicas e comportamentais para garantir o alinhamento do candidato com a posição e cultura da empresa.',
    'services.process.step4.title': 'Apresentação e fechamento',
    'services.process.step4.description': 'Apresentamos os melhores candidatos com relatórios detalhados.',
    'services.process.cta': 'Conheça mais sobre nosso processo',
    'services.quote': 'Nossa metodologia de headhunting foi desenvolvida para identificar não apenas as habilidades técnicas, mas também o alinhamento cultural que garante contratações duradouras e de alto impacto.',
    'differentials.title': 'Nossos Diferenciais',
    'differentials.subtitle': 'Inovações que transformam o processo de recrutamento e seleção para startups em crescimento.',
    'differentials.international.title': 'Vagas Internacionais',
    'differentials.international.description': 'Busca de talentos na América Latina para posições remotas, incluindo curso intensivo de português para estrangeiros.',
    'differentials.onboarding.title': 'Onboarding Assistido',
    'differentials.onboarding.description': 'Acompanhamento especializado nos primeiros 30 dias, com ajustes de expectativas e feedback contínuo para garantir sucesso.',
    'differentials.guarantee.title': '90 dias de garantia',
    'differentials.guarantee.description': 'Oferecemos uma garantia de 90 dias. Se o profissional contratado sair antes desse período, encontramos outro sem cobrar nada da sua empresa.',
    'about.title': 'Quem Somos',
    'about.description1': 'A Talently é uma startup focada em atender startups em fase de tração e scale-up — empresas que estão crescendo rapidamente, receberam investimento ou estão alcançando altos volumes de vendas, e agora enfrentam o desafio de contratar os talentos certos para continuar expandindo.',
    'about.description2': 'Nossa metodologia inclui match comportamental entre candidato e vaga, priorizando perfis com as soft skills ideais para a função, além de treinamentos gratuitos para candidatos em temas como soft skills, etiqueta profissional, expressão verbal, revisão gramatical e redação comercial.',
    'about.precision.title': 'Precisão',
    'about.precision.description': 'Para cada vaga, entregamos até 5 candidatos altamente qualificados.',
    'about.agility.title': 'Agilidade',
    'about.agility.description': 'Entregamos até 5 profissionais qualificados por vaga em até 7 dias úteis.',
    'about.quality.title': 'Qualidade',
    'about.quality.description': 'Talentos pré-qualificados e alinhados com a cultura da sua empresa.',
    'pricing.title': 'Planos e Investimento',
    'pricing.subtitle': 'Escolha o plano ideal para as necessidades de contratação da sua startup.',
    'pricing.plan1.title': 'Contratação Avulsa',
    'pricing.plan1.description': 'Ideal para startups com necessidades pontuais de contratação.',
    'pricing.plan1.price': 'A partir de R$ 3.500',
    'pricing.plan1.period': 'por vaga',
    'pricing.plan1.included': 'O que está incluído:',
    'pricing.plan1.feature1': 'Até 5 candidatos qualificados',
    'pricing.plan1.feature2': 'Match comportamental',
    'pricing.plan1.feature3': 'Treinamentos gratuitos para candidatos',
    'pricing.plan1.feature4': 'Pagamento após a contratação',
    'pricing.plan1.cta': 'Fale com um consultor',
    'pricing.plan2.title': 'Plano Recorrente',
    'pricing.plan2.description': 'Ideal para startups em fase de crescimento contínuo.',
    'pricing.plan2.price': 'Personalizado',
    'pricing.plan2.period': 'pacotes anuais (mín. 12 meses)',
    'pricing.plan2.included': 'O que está incluído:',
    'pricing.plan2.feature1': 'Pacotes de contratações anuais',
    'pricing.plan2.feature2': 'Preços diferenciados por volume',
    'pricing.plan2.feature3': 'Prioridade nos processos',
    'pricing.plan2.feature4': 'Consultor dedicado',
    'pricing.plan2.cta': 'Fale com um consultor',
    'pricing.plan3.title': 'Serviços Adicionais',
    'pricing.plan3.description': 'Complemente sua estratégia de recrutamento.',
    'pricing.plan3.price': 'Sob consulta',
    'pricing.plan3.period': 'preços personalizados',
    'pricing.plan3.included': 'Serviços disponíveis:',
    'pricing.plan3.feature1': 'Onboarding Assistido (30 dias)',
    'pricing.plan3.feature2': 'Curso de português para estrangeiros',
    'pricing.plan3.cta': 'Saiba mais',
    'pricing.popular': 'MAIS POPULAR',
    'testimonials.title': 'O que nossos clientes dizem',
    'testimonials.subtitle': 'Startups que cresceram com o talento certo no time.',
    'testimonials.testimonial1.quote': 'A Talently transformou nossa forma de contratar. Encontramos perfis que realmente se encaixam na nossa cultura e nos ajudam a crescer.',
    'testimonials.testimonial1.position': 'Co-founder da',
    'testimonials.testimonial2.quote': 'A Talently nos disponibilizou de forma muito rápida e eficiente, dois SDRs que nos ajudou muito na validação do ICP de nosso produto na fase de planejamento de nossa startup.',
    'testimonials.testimonial2.position': 'Co-Fundador da',
    'testimonials.testimonial3.quote': 'Hoje consigo produzir conteúdo para diversas redes sociais, de forma consistente e condizente com a minha proposta e perfil, graças a uma excelente profissional que veio pela Talently',
    'testimonials.testimonial3.position': 'Sócio da',
    'cta.title': 'Pronto para acelerar o crescimento da sua startup com os talentos certos?',
    'cta.subtitle': 'Agende uma reunião com nossos consultores e descubra como a Talently pode transformar seu processo de recrutamento.',
    'cta.button': 'Agendar reunião',
    'footer.company.description': 'Conectando startups aos melhores talentos do mercado para acelerar seu crescimento.',
    'footer.services': 'Serviços',
    'footer.services.headhunter': 'Headhunter',
    'footer.services.onboarding': 'Onboarding Assistido',
    'footer.quickLinks': 'Links Rápidos',
    'footer.quickLinks.about': 'Sobre nós',
    'footer.quickLinks.pricing': 'Planos',
    'footer.quickLinks.differentials': 'Diferenciais',
    'footer.quickLinks.privacy': 'Política de Privacidade',
    'footer.contact': 'Contato',
    'footer.contact.email': 'contato@talently.com.br',
    'footer.contact.phone': '(19) 99741-6289',
    'footer.contact.location': 'Campinas, SP - Brasil',
    'footer.copyright': 'Todos os direitos reservados.',
    'login.title': 'Acessar',
    'login.subtitle': 'Insira seu e-mail e senha para acessar sua conta.',
    'login.email': 'E-mail',
    'login.password': 'Senha',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.submit': 'Entrar',
    'login.loading': 'Entrando...',
    'login.noAccount': 'Não tem uma conta?',
    'login.signUpLink': 'Cadastre-se aqui',
    'login.success': 'Login realizado com sucesso!',
    'login.welcome': 'Bem-vindo ao Talently',
    'login.error': 'Erro no login',
    'login.incorrectCredentials': 'E-mail ou senha incorretos',
    'login.tryAgain': 'Tente novamente mais tarde'
  },
  en: {
    'nav.services': 'Services',
    'nav.differentials': 'Differentials',
    'nav.pricing': 'Plans',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'hero.title': 'the right talent to',
    'hero.title.highlight1': 'Hire',
    'hero.title.highlight2': 'accelerate',
    'hero.title.end': 'your company\'s growth',
    'hero.subtitle': 'We connect companies and startups in traction or scale-up phase to highly qualified professionals, focusing on agility and assertiveness in the hiring process.',
    'hero.cta1': 'Schedule a meeting',
    'hero.cta2': 'Learn about our services',
    'services.title': 'Specialized Headhunting',
    'services.subtitle': 'Active search for talent aligned with the behavioral and technical profile of your company, with perfect match for accelerated growth.',
    'services.process.title': 'HOW OUR PROCESS WORKS:',
    'services.process.step1.title': 'Profile Understanding',
    'services.process.step1.description': 'We deeply understand the technical and behavioral needs of your company, organizational culture and business objectives.',
    'services.process.step2.title': 'Qualified Search',
    'services.process.step2.description': 'We use our talent pool and advanced methodologies to find professionals who perfectly fit the defined requirements.',
    'services.process.step3.title': 'Interviews and Selection',
    'services.process.step3.description': 'We conduct technical and behavioral screenings to ensure candidate alignment with the position and company culture.',
    'services.process.step4.title': 'Presentation and Closing',
    'services.process.step4.description': 'We present the best candidates with detailed reports.',
    'services.process.cta': 'Learn more about our process',
    'services.quote': 'Our headhunting methodology was developed to identify not only technical skills, but also cultural alignment that ensures lasting and high-impact hires.',
    'differentials.title': 'Our Differentials',
    'differentials.subtitle': 'Innovations that transform the recruitment and selection process for growing startups.',
    'differentials.international.title': 'International Positions',
    'differentials.international.description': 'Talent search in Latin America for remote positions, including intensive Portuguese course for foreigners.',
    'differentials.onboarding.title': 'Assisted Onboarding',
    'differentials.onboarding.description': 'Specialized support in the first 30 days, with expectation adjustments and continuous feedback to ensure success.',
    'differentials.guarantee.title': '90-day guarantee',
    'differentials.guarantee.description': 'We offer a 90-day guarantee. If the hired professional leaves before this period, we find another one at no cost to your company.',
    'about.title': 'Who We Are',
    'about.description1': 'Talently is a startup focused on serving startups in traction and scale-up phase — companies that are growing rapidly, have received investment or are achieving high sales volumes, and now face the challenge of hiring the right talent to continue expanding.',
    'about.description2': 'Our methodology includes behavioral matching between candidate and position, prioritizing profiles with ideal soft skills for the role, plus free training for candidates on topics such as soft skills, professional etiquette, verbal expression, grammar review and commercial writing.',
    'about.precision.title': 'Precision',
    'about.precision.description': 'For each position, we deliver up to 5 highly qualified candidates.',
    'about.agility.title': 'Agility',
    'about.agility.description': 'We deliver up to 5 qualified professionals per position within 7 business days.',
    'about.quality.title': 'Quality',
    'about.quality.description': 'Pre-qualified talents aligned with your company culture.',
    'pricing.title': 'Plans and Investment',
    'pricing.subtitle': 'Choose the ideal plan for your startup\'s hiring needs.',
    'pricing.plan1.title': 'One-time Hiring',
    'pricing.plan1.description': 'Ideal for startups with specific hiring needs.',
    'pricing.plan1.price': 'Starting at £2,500',
    'pricing.plan1.period': 'per position',
    'pricing.plan1.included': 'What\'s included:',
    'pricing.plan1.feature1': 'Up to 5 qualified candidates',
    'pricing.plan1.feature2': 'Behavioral matching',
    'pricing.plan1.feature3': 'Free candidate training',
    'pricing.plan1.feature4': 'Payment after hiring',
    'pricing.plan1.cta': 'Talk to a consultant',
    'pricing.plan2.title': 'Recurring Plan',
    'pricing.plan2.description': 'Ideal for startups in continuous growth phase.',
    'pricing.plan2.price': 'Customized',
    'pricing.plan2.period': 'annual packages (min. 12 months)',
    'pricing.plan2.included': 'What\'s included:',
    'pricing.plan2.feature1': 'Annual hiring packages',
    'pricing.plan2.feature2': 'Volume-based pricing',
    'pricing.plan2.feature3': 'Process priority',
    'pricing.plan2.feature4': 'Dedicated consultant',
    'pricing.plan2.cta': 'Talk to a consultant',
    'pricing.plan3.title': 'Additional Services',
    'pricing.plan3.description': 'Complement your recruitment strategy.',
    'pricing.plan3.price': 'Upon consultation',
    'pricing.plan3.period': 'customized pricing',
    'pricing.plan3.included': 'Available services:',
    'pricing.plan3.feature1': 'Assisted Onboarding (30 days)',
    'pricing.plan3.feature2': 'Portuguese course for foreigners',
    'pricing.plan3.cta': 'Learn more',
    'pricing.popular': 'MOST POPULAR',
    'testimonials.title': 'What our clients say',
    'testimonials.subtitle': 'Startups that grew with the right talent on the team.',
    'testimonials.testimonial1.quote': 'Talently transformed our hiring process. We found profiles that truly fit our culture and help us grow.',
    'testimonials.testimonial1.position': 'Co-founder of',
    'testimonials.testimonial2.quote': 'Talently provided us very quickly and efficiently with two SDRs that helped us a lot in validating our product ICP during the planning phase of our startup.',
    'testimonials.testimonial2.position': 'Co-Founder of',
    'testimonials.testimonial3.quote': 'Today I can produce content for various social networks, consistently and in line with my proposal and profile, thanks to an excellent professional who came through Talently',
    'testimonials.testimonial3.position': 'Partner at',
    'cta.title': 'Ready to accelerate your startup\'s growth with the right talent?',
    'cta.subtitle': 'Schedule a meeting with our consultants and discover how Talently can transform your recruitment process.',
    'cta.button': 'Schedule meeting',
    'footer.company.description': 'Connecting startups to the best talent in the market to accelerate their growth.',
    'footer.services': 'Services',
    'footer.services.headhunter': 'Headhunter',
    'footer.services.onboarding': 'Assisted Onboarding',
    'footer.quickLinks': 'Quick Links',
    'footer.quickLinks.about': 'About Us',
    'footer.quickLinks.pricing': 'Plans',
    'footer.quickLinks.differentials': 'Differentials',
    'footer.quickLinks.privacy': 'Privacy Policy',
    'footer.contact': 'Contact',
    'footer.contact.email': 'contact@talentlyrecruiter.co.uk',
    'footer.contact.phone': '+44 7917 288150',
    'footer.contact.location': 'London, UK',
    'footer.copyright': 'All rights reserved.',
    'login.title': 'Sign In',
    'login.subtitle': 'Enter your email and password to access your account.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.loading': 'Signing in...',
    'login.noAccount': 'Don\'t have an account?',
    'login.signUpLink': 'Sign up here',
    'login.success': 'Login successful!',
    'login.welcome': 'Welcome to Talently',
    'login.error': 'Login error',
    'login.incorrectCredentials': 'Incorrect email or password',
    'login.tryAgain': 'Please try again later'
  },
  es: {
    'nav.services': 'Servicios',
    'nav.differentials': 'Diferenciales',
    'nav.pricing': 'Planes',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'hero.title': 'el talento adecuado para',
    'hero.title.highlight1': 'Contrata',
    'hero.title.highlight2': 'acelerar',
    'hero.title.end': 'el crecimiento de tu empresa',
    'hero.subtitle': 'Conectamos empresas y startups en fase de tracción o scale-up con profesionales altamente calificados, enfocándonos en agilidad y asertividad en el proceso de contratación.',
    'hero.cta1': 'Agendar reunión',
    'hero.cta2': 'Conoce nuestros servicios',
    'services.title': 'Headhunting Especializado',
    'services.subtitle': 'Búsqueda activa de talentos alineados con el perfil conductual y técnico de tu empresa, con match perfecto para crecimiento acelerado.',
    'services.process.title': 'CÓMO FUNCIONA NUESTRO PROCESO:',
    'services.process.step1.title': 'Entendimiento del perfil',
    'services.process.step1.description': 'Comprendemos profundamente las necesidades técnicas y conductuales de tu empresa, cultura organizacional y objetivos de negocio.',
    'services.process.step2.title': 'Búsqueda calificada',
    'services.process.step2.description': 'Utilizamos nuestro banco de talentos y metodologías avanzadas para encontrar profesionales que se ajusten perfectamente a los requisitos definidos.',
    'services.process.step3.title': 'Entrevistas y selección',
    'services.process.step3.description': 'Realizamos filtros técnicos y conductuales para garantizar la alineación del candidato con la posición y cultura de la empresa.',
    'services.process.step4.title': 'Presentación y cierre',
    'services.process.step4.description': 'Presentamos los mejores candidatos con informes detallados.',
    'services.process.cta': 'Conoce más sobre nuestro proceso',
    'services.quote': 'Nuestra metodología de headhunting fue desarrollada para identificar no solo las habilidades técnicas, sino también la alineación cultural que garantiza contrataciones duraderas y de alto impacto.',
    'differentials.title': 'Nuestros Diferenciales',
    'differentials.subtitle': 'Innovaciones que transforman el proceso de reclutamiento y selección para startups en crecimiento.',
    'differentials.international.title': 'Vacantes Internacionales',
    'differentials.international.description': 'Búsqueda de talentos en América Latina para posiciones remotas, incluyendo curso intensivo de portugués para extranjeros.',
    'differentials.onboarding.title': 'Onboarding Asistido',
    'differentials.onboarding.description': 'Acompañamiento especializado en los primeros 30 días, con ajustes de expectativas y feedback continuo para garantizar el éxito.',
    'differentials.guarantee.title': '90 días de garantía',
    'differentials.guarantee.description': 'Ofrecemos una garantía de 90 días. Si el profesional contratado se va antes de este período, encontramos otro sin costo alguno para tu empresa.',
    'about.title': 'Quiénes Somos',
    'about.description1': 'Talently es una startup enfocada en atender startups en fase de tracción y scale-up — empresas que están creciendo rápidamente, han recibido inversión o están alcanzando altos volúmenes de ventas, y ahora enfrentan el desafío de contratar los talentos adecuados para continuar expandiéndose.',
    'about.description2': 'Nuestra metodología incluye match conductual entre candidato y vacante, priorizando perfiles con las soft skills ideales para la función, además de entrenamientos gratuitos para candidatos en temas como soft skills, etiqueta profesional, expresión verbal, revisión gramatical y redacción comercial.',
    'about.precision.title': 'Precisión',
    'about.precision.description': 'Para cada vacante, entregamos hasta 5 candidatos altamente calificados.',
    'about.agility.title': 'Agilidad',
    'about.agility.description': 'Entregamos hasta 5 profesionales calificados por vacante en hasta 7 días hábiles.',
    'about.quality.title': 'Calidad',
    'about.quality.description': 'Talentos pre-calificados y alineados con la cultura de tu empresa.',
    'pricing.title': 'Planes e Inversión',
    'pricing.subtitle': 'Elige el plan ideal para las necesidades de contratación de tu startup.',
    'pricing.plan1.title': 'Contratación Única',
    'pricing.plan1.description': 'Ideal para startups con necesidades puntuales de contratación.',
    'pricing.plan1.price': 'Desde €2.000',
    'pricing.plan1.period': 'por vacante',
    'pricing.plan1.included': 'Qué está incluido:',
    'pricing.plan1.feature1': 'Hasta 5 candidatos calificados',
    'pricing.plan1.feature2': 'Match conductual',
    'pricing.plan1.feature3': 'Entrenamientos gratuitos para candidatos',
    'pricing.plan1.feature4': 'Pago después de la contratación',
    'pricing.plan1.cta': 'Habla con un consultor',
    'pricing.plan2.title': 'Plan Recurrente',
    'pricing.plan2.description': 'Ideal para startups en fase de crecimiento continuo.',
    'pricing.plan2.price': 'Personalizado',
    'pricing.plan2.period': 'paquetes anuales (mín. 12 meses)',
    'pricing.plan2.included': 'Qué está incluido:',
    'pricing.plan2.feature1': 'Paquetes de contrataciones anuales',
    'pricing.plan2.feature2': 'Precios diferenciados por volumen',
    'pricing.plan2.feature3': 'Prioridad en los procesos',
    'pricing.plan2.feature4': 'Consultor dedicado',
    'pricing.plan2.cta': 'Habla con un consultor',
    'pricing.plan3.title': 'Servicios Adicionales',
    'pricing.plan3.description': 'Complementa tu estrategia de reclutamiento.',
    'pricing.plan3.price': 'Bajo consulta',
    'pricing.plan3.period': 'precios personalizados',
    'pricing.plan3.included': 'Servicios disponibles:',
    'pricing.plan3.feature1': 'Onboarding Asistido (30 días)',
    'pricing.plan3.feature2': 'Curso de portugués para extranjeros',
    'pricing.plan3.cta': 'Saber más',
    'pricing.popular': 'MÁS POPULAR',
    'testimonials.title': 'Lo que dicen nuestros clientes',
    'testimonials.subtitle': 'Startups que crecieron con el talento adecuado en el equipo.',
    'testimonials.testimonial1.quote': 'Talently transformó nuestra forma de contratar. Encontramos perfiles que realmente se ajustan a nuestra cultura y nos ayudan a crecer.',
    'testimonials.testimonial1.position': 'Co-fundador de',
    'testimonials.testimonial2.quote': 'Talently nos proporcionó de forma muy rápida y eficiente, dos SDRs que nos ayudaron mucho en la validación del ICP de nuestro producto en la fase de planificación de nuestra startup.',
    'testimonials.testimonial2.position': 'Co-Fundador de',
    'testimonials.testimonial3.quote': 'Hoy puedo producir contenido para diversas redes sociales, de forma consistente y acorde con mi propuesta y perfil, gracias a una excelente profesional que vino por Talently',
    'testimonials.testimonial3.position': 'Socio de',
    'cta.title': '¿Listo para acelerar el crecimiento de tu startup con los talentos adecuados?',
    'cta.subtitle': 'Agenda una reunión con nuestros consultores y descubre cómo Talently puede transformar tu proceso de reclutamiento.',
    'cta.button': 'Agendar reunión',
    'footer.company.description': 'Conectando startups con los mejores talentos del mercado para acelerar su crecimiento.',
    'footer.services': 'Servicios',
    'footer.services.headhunter': 'Headhunter',
    'footer.services.onboarding': 'Onboarding Asistido',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.quickLinks.about': 'Acerca de',
    'footer.quickLinks.pricing': 'Planes',
    'footer.quickLinks.differentials': 'Diferenciales',
    'footer.quickLinks.privacy': 'Política de Privacidad',
    'footer.contact': 'Contacto',
    'footer.contact.email': 'contacto@talentlyrecruiter.es',
    'footer.contact.phone': '+34 123 456 789',
    'footer.contact.location': 'Madrid, España',
    'footer.copyright': 'Todos los derechos reservados.',
    'login.title': 'Acceder',
    'login.subtitle': 'Ingresa tu email y contraseña para acceder a tu cuenta.',
    'login.email': 'Email',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste la contraseña?',
    'login.submit': 'Ingresar',
    'login.loading': 'Ingresando...',
    'login.noAccount': '¿No tienes una cuenta?',
    'login.signUpLink': 'Regístrate aquí',
    'login.success': '¡Inicio de sesión exitoso!',
    'login.welcome': 'Bienvenido a Talently',
    'login.error': 'Error de inicio de sesión',
    'login.incorrectCredentials': 'Email o contraseña incorrectos',
    'login.tryAgain': 'Inténtalo de nuevo más tarde'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('talently-language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('talently-language', language);
  }, [language]);

  const toggleLanguage = () => {
    const languages: Language[] = ['pt', 'en', 'es'];
    const currentIndex = languages.indexOf(language);
    const nextIndex = (currentIndex + 1) % languages.length;
    setLanguage(languages[nextIndex]);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
